name: eks-tf
on:
  workfworkflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      AWS_SESSION_TOKEN: ${{secrets.AWS_SESSION_TOKEN}}
      SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout repo
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: $AWS_ACCESS_KEY_ID
          aws-secret-access-key: $AWS_SECRET_ACCESS_KEY
          aws-session-token: $AWS_SESSION_TOKEN
          aws-region: us-east-2
          # role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          # role-external-id: ${{ secrets.AWS_ROLE_EXTERNAL_ID }}
          role-duration-seconds: 3600
          role-session-name: DeployTF
      - name: TF Apply
        working-directory: ./deploy/kubernetes/terraform
        run: TF_VAR_private_key_path="$SSH_PRIVATE_KEY" terraform apply -auto-approve
